from __future__ import annotations

from datetime import datetime, timezone

from providers.base import ProviderRequest, ProviderResponse


class MockProvider:
    id = "mock"

    def generate(self, request: ProviderRequest) -> ProviderResponse:
        title = request.context.get("title") or request.prompt[:80] or "AI delivery output"
        content = (
            f"# {title}\n\n"
            f"Generated by `{request.agent_id}` using the deterministic mock provider.\n\n"
            "## Summary\n\n"
            "This MVP output is template-driven and ready for future provider replacement.\n\n"
            "## Next Actions\n\n"
            "- Review generated artifacts.\n"
            "- Approve the relevant gate before execution.\n"
        )
        return ProviderResponse(
            content=content,
            metadata={
                "provider": self.id,
                "generated_at": datetime.now(timezone.utc).isoformat(),
            },
        )

